[package]
name = "imgui-rs-vulkan-renderer"
description = "A Vulkan renderer for imgui-rs using Ash."
readme = "README.md"
keywords = ["imgui", "vulkan", "ash"]
homepage = "https://github.com/adrien-ben/imgui-rs-vulkan-renderer"
repository = "https://github.com/adrien-ben/imgui-rs-vulkan-renderer"
documentation = "https://docs.rs/imgui-rs-vulkan-renderer"
license = "MIT"
version = "0.7.0"
authors = ["Adrien Bennadji <adrien.bennadji@live.fr>"]
edition = "2018"

exclude = [
    "assets/*",
    "compile_shaders.*"
]

[dependencies]
log = "0.4"
imgui = "^0.7"
ash = ">=0.29"
ultraviolet = "0.8"
vk-mem = {version = "0.2", optional = true}

[features]
vkmem = ["vk-mem"]

[dev-dependencies]
simple_logger = "1.11"
winit = "0.24"
imgui-winit-support = "^0.7"
ash = "0.32"
ash-window = "0.6"
image = "0.23"
imgui-rs-vulkan-renderer = { path = ".", features = ["vkmem"]}
