[package]
name = "imgui-rs-vulkan-renderer"
description = "A Vulkan renderer for imgui-rs using Ash."
readme = "README.md"
keywords = ["imgui", "vulkan", "ash"]
homepage = "https://github.com/adrien-ben/imgui-rs-vulkan-renderer"
repository = "https://github.com/adrien-ben/imgui-rs-vulkan-renderer"
documentation = "https://docs.rs/imgui-rs-vulkan-renderer"
license = "MIT"
version = "1.0.0"
authors = ["Adrien Bennadji <adrien.bennadji@live.fr>"]
edition = "2018"

exclude = [
    "assets/*",
    "compile_shaders.*"
]

[dependencies]
thiserror = "1.0"
log = "0.4"
imgui = "^0.8"
ash = "0.34"
ultraviolet = "0.8" 

gpu-allocator = { version = "0.12", default-features = false, features = ["vulkan"], optional = true }

[dev-dependencies]
simple_logger = "1.11"
winit = "0.26.0"
imgui-winit-support = { version = "^0.8", default-features = false, features = ["winit-26"] }
ash = "0.34"
ash-window = "0.8"
image = "0.23"
imgui-rs-vulkan-renderer = { path = ".", features = ["gpu-allocator"] }
