name: Publish

on:
  push:
    tags: 
      - '*'

jobs:
  build:
    name: Publish
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - name: Publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.cratesio_token }}
